import Groq from 'groq-sdk';
import { RawNewsItem } from './fetch-news.js';
import { SYSTEM_PROMPT } from './constants.js';
import dotenv from 'dotenv';

dotenv.config();

// --- CONFIGURATION ---
// User can provide up to 3 Groq Keys
const KEY_1 = process.env.GROQ_API_KEY_1 || process.env.GROQ_API_KEY; // Support legacy single key
const KEY_2 = process.env.GROQ_API_KEY_2;
const KEY_3 = process.env.GROQ_API_KEY_3;

const AVAILABLE_KEYS = [KEY_1, KEY_2, KEY_3].filter(Boolean) as string[];

if (AVAILABLE_KEYS.length === 0) {
    console.error('FATAL: No GROQ_API_KEY found in .env. Please add GROQ_API_KEY_1, _2, _3');
    process.exit(1);
}

export interface ProcessedArticle {
    title: string;
    excerpt: string;
    content: string;
    tags: string[];
    original_url: string;
    source: string;
    category: string;
    secondary_category?: string | null;
    image_prompt: string;
}

export async function processNewsItem(item: RawNewsItem): Promise<ProcessedArticle | null> {
    const prompt = `
    Original Title: ${item.title}
    Original Content: ${item.content}
    Original Category: ${item.category}
    
    Rewrite this article following the system instructions.
    `;

    // Strategy: Try keys in order.
    // Key 1 & 2 -> Use Llama 70b (High Quality)
    // Key 3 -> Use Llama 8b (High Speed/Fallback) OR if we run out of keys, force 8b on last key

    let attempts = 0;
    const maxAttempts = AVAILABLE_KEYS.length * 2; // Allow looping twice if needed, but switching keys

    while (attempts < maxAttempts) {
        // Round Robin rotation
        const keyIndex = attempts % AVAILABLE_KEYS.length;
        const currentKey = AVAILABLE_KEYS[keyIndex];

        // Determine Model: 
        // If it's the LAST key in our list (Key 3), use 8b. 
        // Otherwise use 70b.
        const isFallbackKey = (keyIndex === AVAILABLE_KEYS.length - 1) && (AVAILABLE_KEYS.length > 1);
        const model = isFallbackKey ? 'llama-3.1-8b-instant' : 'llama-3.3-70b-versatile';

        const groq = new Groq({ apiKey: currentKey });

        try {
            console.log(`[AI] Processing: "${item.title.substring(0, 20)}..."`);
            console.log(`     Using Key #${keyIndex + 1} | Model: ${model} `);

            const completion = await groq.chat.completions.create({
                messages: [
                    { role: 'system', content: SYSTEM_PROMPT },
                    { role: 'user', content: prompt }
                ],
                model: model,
                temperature: 0.7,
                max_tokens: 8000,
                response_format: { type: "json_object" }, // Strict JSON
            });

            const responseText = completion.choices[0]?.message?.content || '';

            // Clean & Parse
            const jsonMatch = responseText.match(/\{[\s\S]*\}/);
            const cleanText = jsonMatch ? jsonMatch[0] : responseText;

            let data;
            try {
                data = JSON.parse(cleanText);
            } catch (e) {
                console.warn(`[AI] JSON Parse Fail on Key #${keyIndex + 1}. Retrying...`);
                throw new Error('Invalid JSON response'); // Trigger retry/rotation
            }

            return {
                title: data.title,
                excerpt: data.excerpt,
                content: data.content,
                tags: data.tags || [],
                original_url: item.link,
                source: item.source,
                // Use AI-determined categories (Fallback to RSS category if missing)
                category: data.category || item.category,
                secondary_category: data.secondary_category || null,
                // Use the strict prompt generated by LLM, or fallback to Title
                image_prompt: data.image_prompt || item.title
            };

        } catch (error: any) {
            const isRateLimit = error.message?.includes('rate') || error.status === 429 || error.message?.includes('429');
            const isJsonError = error.message === 'Invalid JSON response';

            if (isRateLimit) {
                console.warn(`[Groq] Rate Limit Hit on Key #${keyIndex + 1} (429).Switching to next key...`);
                attempts++;
                continue; // Loop will pick next key
            } else if (isJsonError) {
                // If 70b fails JSON, switching to 8b (last key) might fix it as 8b is faster/different
                console.warn(`[Groq] JSON Error.Switching key to try valid generation...`);
                attempts++;
                continue;
            }

            console.error('[AI] Fatal Error:', error.message || error);
            // If it's a fatal non-rate-limit error (like Auth), we might want to try next key too?
            // Assuming 401 (Auth) means bad key -> Try next.
            if (error.status === 401) {
                console.warn(`[Groq] Invalid Key #${keyIndex + 1}. Removing from rotation...`);
                attempts++;
                continue;
            }

            return null; // Unknown error, abort
        }
    }

    console.error('[AI] All keys exhausted/rate-limited. Skipping article.');
    return null;
}
